root: true
env:
  node: true
  es2021: true
  browser: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:eslint-comments/recommended
  - plugin:jsonc/recommended-with-jsonc
  - plugin:markdown/recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - './.eslintrc-auto-import.json'
settings:
  'import/resolver':
    node:
      extensions: ['.js', '.mjs', '.ts', '.d.ts', '.tsx']
overrides:
  - files:
      - '*.json'
      - '*.json5'
      - '*.jsonc'
    parser: jsonc-eslint-parser
  - files:
      - 'package.json'
    parser: jsonc-eslint-parser
    rules:
      'jsonc/sort-keys':
        - error
        - pathPattern: '^$'
          order:
            - name
            - version
            - private
            - packageManager
            - description
            - type
            - keywords
            - homepage
            - bugs
            - license
            - author
            - contributors
            - funding
            - files
            - main
            - module
            - exports
            - unpkg
            - jsdelivr
            - browser
            - bin
            - man
            - directories
            - repository
            - publishConfig
            - scripts
            - peerDependencies
            - peerDependenciesMeta
            - optionalDependencies
            - dependencies
            - devDependencies
            - engines
            - config
            - overrides
            - pnpm
            - husky
            - lint-staged
            - eslintConfig
        - pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies$'
          order:
            type: asc
  - files:
      - '*.js'
      - '*.cjs'
    rules:
      '@typescript-eslint/no-var-requires': off
  - files:
      - '*.vue'
    parser: vue-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.vue']
      ecmaVersion: 'latest'
      ecmaFeatures:
        jsx: true
rules:
  prettier/prettier: error

  import/order:
  - error
  - groups:
      - builtin
      - external
      - internal
      - parent
      - sibling
      - index
      - object
      - type
    pathGroups:
      - pattern: vue
        group: external
        position: before
      - pattern: "@eadmin/**"
        group: internal
    pathGroupsExcludedImportTypes:
      - type
  import/no-unresolved: off

  vue/multi-word-component-names: off

  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-explicit-any': off
