/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconEpMoon: typeof import('~icons/ep/moon')['default']
    IconEpSun: typeof import('~icons/ep/sun')['default']
    IconEpSunny: typeof import('~icons/ep/sunny')['default']
    IconLocalDingtalk: typeof import('~icons/local/dingtalk')['default']
    IconLocalWechat: typeof import('~icons/local/wechat')['default']
    IconMdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    IconMdiLockOutline: typeof import('~icons/mdi/lock-outline')['default']
    IconMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IconMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    IconMdiWeb: typeof import('~icons/mdi/web')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
